export interface Supporter {
  name: string;
  logo: string;
  alt: string;
  width?: number;
  height?: number;
}

export const supporters: Supporter[] = [
  {
    name: 'Globe',
    logo: '/logos/Globe.png',
    alt: 'Globe Logo',
    width: 64,
    height: 64,
  },
  {
    name: 'GDG Chapters',
    logo: '/logos/GDG.png',
    alt: 'GDG Logo',
    width: 64,
    height: 64,
  },
  {
    name: 'DataCamp',
    logo: '/logos/DataCamp.png',
    alt: 'DataCamp Logo',
    width: 64,
    height: 64,
  },
  {
    name: 'FullScale',
    logo: '/logos/FullScale.png',
    alt: 'FullScale Logo',
    width: 64,
    height: 64,
  },
  {
    name: 'StellarPH',
    logo: '/logos/StellarPH.png',
    alt: 'StellarPH Logo',
    width: 64,
    height: 64,
  },
  {
    name: 'DevCon',
    logo: '/logos/DevCon.png',
    alt: 'DevCon Logo',
    width: 64,
    height: 64,
  },
  {
    name: 'Hatchit',
    logo: '/logos/Hatchit.png',
    alt: 'Hatchit Logo',
    width: 64,
    height: 64,
  },
  {
    name: 'LifeSmart',
    logo: '/logos/LifeSmart.png',
    alt: 'LifeSmart Logo',
    width: 64,
    height: 64,
  },
  {
    name: 'Mata Technologies',
    logo: '/logos/Mata.png',
    alt: 'Mata Technologies Logo',
    width: 64,
    height: 64,
  },
  {
    name: 'Enspace',
    logo: '/logos/Enspace.png',
    alt: 'Enspace Logo',
    width: 64,
    height: 64,
  },
  {
    name: 'Sandbox Foundation',
    logo: '/logos/Sandbox.png',
    alt: 'Sandbox Foundation Logo',
    width: 64,
    height: 64,
  },
  {
    name: 'Lexmark',
    logo: '/logos/Lexmark.png',
    alt: 'Lexmark Logo',
    width: 64,
    height: 64,
  },
  {
    name: 'Notion',
    logo: '/logos/Notion.png',
    alt: 'Notion Logo',
    width: 64,
    height: 64,
  },
  {
    name: 'Brewlab',
    logo: '/logos/Brewlab.png',
    alt: 'Brewlab Logo',
    width: 64,
    height: 64,
  },
  {
    name: 'But First, Coffee',
    logo: '/logos/But First.png',
    alt: 'But First, Coffee Logo',
    width: 64,
    height: 64,
  },
  {
    name: 'USC Chemical Engineering Club',
    logo: '/logos/Chem Club.png',
    alt: 'USC Chemical Engineering Club Logo',
    width: 64,
    height: 64,
  },
  {
    name: 'UP Society of Computer Scientists',
    logo: '/logos/UPCS.png',
    alt: 'UP Society of Computer Scientists Logo',
    width: 64,
    height: 64,
  },
  {
    name: 'USC Collegiate Engineering Council',
    logo: '/logos/USC CEC.png',
    alt: 'USC Collegiate Engineering Council Logo',
    width: 64,
    height: 64,
  },
  {
    name: 'Computer Engineering Council',
    logo: '/logos/CpeC.png',
    alt: 'Computer Engineering Council',
    width: 64,
    height: 64,
  },
  {
    name: 'CISCO',
    logo: '/logos/CISCO.png',
    alt: 'CISCO Logo',
    width: 64,
    height: 64,
  },
  {
    name: 'CoDE USC',
    logo: '/logos/CoDE.png',
    alt: 'CoDE USC Logo',
    width: 64,
    height: 64,
  },
  {
    name: 'Innovare',
    logo: '/logos/Innovare.png',
    alt: 'Innovare Logo',
    width: 64,
    height: 64,
  },
  {
    name: 'PrintKids',
    logo: '/logos/PrintKids.png',
    alt: 'PrintKids Logo',
    width: 64,
    height: 64,
  },
  {
    name: 'SAS Royale',
    logo: '/logos/SAS Royale.png',
    alt: 'SAS Royale Logo',
    width: 64,
    height: 64,
  },
  {
    name: 'Timetable Lounge',
    logo: '/logos/Timetable.png',
    alt: 'Timetable Lounge Logo',
    width: 64,
    height: 64,
  },
];
